#!/usr/bin/with-contenv bash

	screen -D -m -S \
	rtorrent s6-setuidgid abc /usr/local/bin/rtorrent \
	-n -o import=/config/rtorrent/rtorrent.rc

until [ -e "/config/rtorrent/rtorrent_sess/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(< /config/rtorrent/rtorrent_sess/rtorrent.lock cut -d '+' -f 2)
tail -n 1 -f /config/rtorrent/log/rtorrent.log --pid "$rtorrent_pid"
