#!/usr/bin/with-contenv bash

# make folders (Original)
mkdir -p /downloads{/completed,/incoming,/watched} \
	 /config/tmp 
	 /detach_sess


# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown abc:abc /downloads
chmod 755 /usr/local/bin/curl
