#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/tmp /detach_sess

# create rtorrent log file
touch /config/rtorrent/log/rtorrent.log

# set perms
chown abc:abc -R /config /detach_sess
chown abc:abc /downloads
